    # The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
    modLoader="javafml"
    # A version range to match for said mod loader - for regular FML @Mod it will be the forge version
    # Forge for 1.15.2 is version 31
    loaderVersion="[34,)"
    
    license="All rights reserved"
    # If the mods defined in this file should show as seperate resource packs
    showAsResourcePack=false

    [[mods]]
    modId="icecontrol"
    version="1.0.0"
    displayName="Ice Control"
    authors="CodeWolf219"
    description='''
    Allows control of when/if ice melts and if it turns to water after breaking
    '''